WIP: add vpn commands
pluralsh/plural-cli pull request #246
Opened 2022-10-28 16:30 UTC by DavidSpek

Work in progress
## Summary
Adds commands for listing VPN servers (although there should only be one), list the clients of a particular server, creating a new vpn client for a server and getting the configuration of a client.

## Labels

## Test Plan

## Checklist

- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a meaningful title and summary to convey the impact of this PR to a user.
- [ ] I have added relevant labels to this PR to help with categorization for release notes.

2022-11-02 00:41 UTC, michaeljguarino commented on cmd/plural/vpn.go
> +	if err := p.InitKube(); err != nil {
A lot of these functions seem to init kube and checkIfVPNInstalled, perhaps we should make a wrapper func like we have for some other stuff like `rooted` elsewhere to remove duplicate code.

2022-11-02 13:40 UTC, zreigz requested changes

2022-11-02 13:40 UTC, zreigz commented on cmd/plural/vpn.go
> +		return utils.HighlightError(fmt.Errorf("wireguard is not installed. run `plural bundle list wireguard` to find the bundle to install"))
you can extract this sentence to the const, it's used in 4 places

2022-11-02 13:42 UTC, zreigz commented
Generally, everything works fine :+1:

2022-11-02 14:27 UTC, DavidSpek commented on cmd/plural/vpn.go
> +		err := utils.WriteFile(c.String("path")+peer.Name+".conf", peerConfig)
Yeah that's probably better. I'll change that.

2022-11-03 08:48 UTC, zreigz approved these changes
lgtm

2022-11-03 08:49 UTC, merged