Cluster Ownership transfer
pluralsh/plural-cli pull request #398
Opened 2023-04-14 20:12 UTC by michaeljguarino

## Summary
This has three phases:
* call ownership transfer api to sync all installations
* overwrite owner entry in workspace.yaml
* rebuild bootstrap and console to resync docker creds and rewire the console to use new owner

## Test Plan
trying to find a strategy to test it end-to-end

## Checklist

- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a meaningful title and summary to convey the impact of this PR to a user.
- [ ] I have added relevant labels to this PR to help with categorization for release notes.

2023-04-17 06:01 UTC, zreigz requested changes

2023-04-17 06:01 UTC, zreigz commented on cmd/plural/plural.go
> +		return err
use `api.GetErrorResponse`

2023-04-24 15:24 UTC, michaeljguarino commented
@zreigz PTAL

2023-04-24 15:25 UTC, zreigz approved these changes
lgtm

2023-04-24 15:50 UTC, merged